# Generated by Django 3.2.15 on 2023-09-07 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='уникальный адрес для тега', unique=True, validators=[django.core.validators.RegexValidator(message='тег содержит недопустимый символ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
    ]
